# Generated by Django 5.0.6 on 2024-06-05 19:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.JSONField()),
                ('weather', models.JSONField()),
                ('base', models.JSONField()),
                ('main', models.JSONField()),
                ('visibility', models.JSONField()),
                ('wind', models.JSONField()),
                ('rain', models.JSONField()),
                ('clouds', models.JSONField()),
                ('dt', models.JSONField()),
                ('sys', models.JSONField()),
                ('timezone', models.JSONField()),
                ('name', models.JSONField()),
                ('cod', models.JSONField()),
            ],
            options={
                'managed': False,
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='TransientModel',
        ),
    ]
