# Generated by Django 5.0.6 on 2024-06-08 21:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="inventory",
            name="decrement_item_qty_trigger",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="item_bin",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item_bulk",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item_consumable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item_qty",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item_weight",
            field=models.FloatField(default=1.0),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventory",
            trigger=pgtrigger.compiler.Trigger(
                name="decrement_item_qty_trigger",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n        BEGIN\n            IF NEW.item_qty = 0 THEN\n                DELETE FROM inventory_inventory WHERE item_id = OLD.id;\n            END IF;\n            RETURN NEW;\n        END;\n        ",
                    hash="ace5c29563596a2f8baa2d561371ba34102ad0f3",
                    operation="UPDATE",
                    pgid="pgtrigger_decrement_item_qty_trigger_c958b",
                    table="inventory_inventory",
                    when="BEFORE",
                ),
            ),
        ),
    ]
