# Generated by Django 5.0.6 on 2024-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_decrement_item_qty_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
