# Generated by Django 5.0.6 on 2024-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_owner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=225),
        ),
    ]
