# Generated by Django 5.0.6 on 2024-06-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_item_owner_alter_inventory_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_owner',
            field=models.CharField(default='system', max_length=255),
        ),
    ]
