# Generated by Django 5.0.6 on 2024-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_owner',
            field=models.IntegerField(default=0),
        ),
    ]
