# Generated by Django 5.0.6 on 2024-06-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventory_item_owner_and_more'),
        ('omnipresence', '0003_remove_omnipresencemodel_update_character_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel'),
        ),
    ]
