# Generated by Django 5.0.6 on 2024-06-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_item_name'),
        ('omnipresence', '0004_remove_omnipresencemodel_update_character_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
