# Generated by Django 5.0.6 on 2024-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_item_owner_alter_inventory_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_bytestring',
            field=models.BinaryField(default=b'\x08'),
        ),
    ]
