# Generated by Django 5.0.6 on 2024-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventory_item_bytestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_bytestring',
            field=models.BinaryField(default=b'\x08', editable=True),
        ),
    ]
