# Generated by Django 5.0.6 on 2024-06-11 19:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_item_bytestring'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='inventory',
            name='decrement_item_qty_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='calculate_item_bulk', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                UPDATE inventory_inventory\n                SET item_bulk = NEW.item_qty * item_weight\n                WHERE item_id = OLD.id;\n                RETURN NEW;\n            END;\n        ', hash='15628caebf9cf9bdde2b82e86bf3f809435b6d8a', operation='UPDATE', pgid='pgtrigger_calculate_item_bulk_acc05', table='inventory_inventory', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='decrement_item_qty_trigger', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                IF NEW.item_qty = 0 THEN\n                    DELETE FROM inventory_inventory WHERE item_id = OLD.id;\n                END IF;\n                RETURN NEW;\n            END;\n        ', hash='2a2d329a2510389192679586109c270c54533404', operation='UPDATE', pgid='pgtrigger_decrement_item_qty_trigger_c958b', table='inventory_inventory', when='BEFORE')),
        ),
    ]
