# Generated by Django 5.0.6 on 2024-06-12 17:03

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_inventory_decrement_item_qty_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='inventory',
            name='calculate_item_bulk',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='calculate_item_bulk', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                UPDATE inventory_inventory\n                SET item_bulk = NEW.item_qty * item_weight\n                WHERE id = OLD.id;\n                RETURN NEW;\n            END;\n        ', hash='6a0dbf1d4571c2152b8682603b953ce08aaa7649', operation='UPDATE', pgid='pgtrigger_calculate_item_bulk_acc05', table='inventory_inventory', when='BEFORE')),
        ),
    ]
