# Generated by Django 5.0.6 on 2024-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_inventory_calculate_item_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_version',
            field=models.CharField(default='1.0.0', max_length=255),
        ),
    ]
