# Generated by Django 5.0.6 on 2024-06-17 21:18

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventory_item_version'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='inventory',
            name='decrement_item_qty_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='decrement_item_qty_trigger', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                IF NEW.item_qty = 0 THEN\n                    DELETE FROM inventory_inventory WHERE inventory_inventory.item_id = OLD.id;\n                END IF;\n                RETURN NEW;\n            END;\n        ', hash='63e9cf9458faf1a5965e7c216fbb55a683f77413', operation='UPDATE', pgid='pgtrigger_decrement_item_qty_trigger_c958b', table='inventory_inventory', when='BEFORE')),
        ),
    ]
