# Generated by Django 5.0.6 on 2024-06-18 13:20

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_inventory_decrement_item_qty_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='inventory',
            name='decrement_item_qty_trigger',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='decrement_item_qty_trigger', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                IF NEW.item_qty = 0 THEN\n                    DELETE FROM inventory_inventory\n                    WHERE id = OLD.id;\n                END IF;\n                RETURN NEW;\n            END;\n        ', hash='67f7d341e59c5173f1afa2c89493cec3c16b2af9', operation='UPDATE', pgid='pgtrigger_decrement_item_qty_trigger_c958b', table='inventory_inventory', when='AFTER')),
        ),
    ]
