# Generated by Django 5.0.6 on 2024-06-21 11:09

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_inventory_decrement_item_qty_trigger_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='detect_inventory_overburden', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                volume int;\n            BEGIN\n                volume := NEW.item_bulk + (SELECT SUM(item_bulk) FROM inventory_inventory WHERE inventory_owner_id = OLD.inventory_owner_id);\n                IF volume >= 10 THEN\n                    RAISE EXCEPTION 'overburdened';\n                END IF;\n                RETURN NEW;\n            END;\n        ", hash='4e61007147d488c18c643e0874c6894b4a96a1bb', operation='UPDATE', pgid='pgtrigger_detect_inventory_overburden_afc87', table='inventory_inventory', when='BEFORE')),
        ),
    ]
