# Generated by Django 5.0.6 on 2024-06-21 11:12

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_inventory_detect_inventory_overburden'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='inventory',
            name='detect_inventory_overburden',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='inventory',
            trigger=pgtrigger.compiler.Trigger(name='detect_inventory_overburden', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                volume int;\n            BEGIN\n                volume := NEW.item_bulk + (SELECT SUM(item_bulk) FROM inventory_inventory WHERE item_owner_id = OLD.item_owner_id);\n                IF volume >= 10 THEN\n                    RAISE EXCEPTION 'overburdened';\n                END IF;\n                RETURN NEW;\n            END;\n        ", hash='b4f4af1c40f13c0349afb18f653936c19c8f552a', operation='UPDATE', pgid='pgtrigger_detect_inventory_overburden_afc87', table='inventory_inventory', when='BEFORE')),
        ),
    ]
