# Generated by Django 5.0.6 on 2024-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('temperature', models.FloatField(default=1.0)),
            ],
        ),
    ]
