# Generated by Django 5.0.6 on 2024-06-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0004_remove_omnipresencemodel_update_character_activity'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personamodel',
            old_name='name',
            new_name='assistant_id',
        ),
        migrations.RemoveField(
            model_name='personamodel',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='personamodel',
            name='temperature',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='assistant_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personamodel',
            name='thread_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personamodel',
            name='thread_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel'),
        ),
    ]
