# Generated by Django 5.0.6 on 2024-06-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0004_remove_omnipresencemodel_update_character_activity'),
        ('persona', '0003_remove_personamodel_assistant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personamodel',
            old_name='thread_id',
            new_name='assistant_name',
        ),
        migrations.RemoveField(
            model_name='personamodel',
            name='thread_owner',
        ),
        migrations.CreateModel(
            name='PersonaThreadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('assistant_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='persona.personamodel')),
                ('thread_owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel')),
            ],
        ),
    ]
