# Generated by Django 5.0.6 on 2024-06-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0004_remove_omnipresencemodel_update_character_activity'),
        ('persona', '0004_rename_thread_id_personamodel_assistant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='asssistant_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel'),
        ),
        migrations.AlterField(
            model_name='personathreadmodel',
            name='assistant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='persona.personamodel'),
        ),
        migrations.AlterField(
            model_name='personathreadmodel',
            name='thread_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='omnipresence.omnipresencemodel'),
        ),
    ]
