# Generated by Django 5.0.6 on 2024-06-10 14:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmnipresenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('charname', models.CharField(max_length=255, unique=True)),
                ('working_dir', models.CharField(max_length=512)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='omnipresencemodel',
            trigger=pgtrigger.compiler.Trigger(name='update_character_activity', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                NEW.is_active = True\n                WHERE\n                    id = NEW.id;\n                ', hash='a49dff74f3c6e3f54ebcab0cdbb485e7406e4769', operation='UPDATE', pgid='pgtrigger_update_character_activity_00ac2', table='omnipresence_omnipresencemodel', when='BEFORE')),
        ),
    ]
