# Generated by Django 5.0.6 on 2024-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmnipresenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('char', models.CharField(max_length=255)),
                ('cwd', models.CharField(max_length=512)),
            ],
        ),
    ]
