# Generated by Django 5.0.6 on 2024-06-10 16:09

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='omnipresencemodel',
            name='update_character_activity',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='omnipresencemodel',
            trigger=pgtrigger.compiler.Trigger(name='update_character_activity', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    NEW.is_active = True\n                    RETURN NEW;\n                ', hash='9726562cfa162cf4d4e81f5601fa16cd9aa011ee', operation='UPDATE', pgid='pgtrigger_update_character_activity_00ac2', table='omnipresence_omnipresencemodel', when='BEFORE')),
        ),
    ]
