# Generated by Django 5.0.6 on 2024-06-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omnipresencemodel',
            old_name='name',
            new_name='user',
        ),
    ]
