# Generated by Django 5.0.6 on 2024-06-10 16:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0002_remove_omnipresencemodel_update_character_activity_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='omnipresencemodel',
            name='update_character_activity',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='omnipresencemodel',
            trigger=pgtrigger.compiler.Trigger(name='update_character_activity', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    NEW.is_active = True;\n                    RETURN NEW;\n                ', hash='64822d566a0af0f7dc4458da937436ef02602694', operation='UPDATE', pgid='pgtrigger_update_character_activity_00ac2', table='omnipresence_omnipresencemodel', when='BEFORE')),
        ),
    ]
