# Generated by Django 5.0.6 on 2024-06-10 18:16

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0002_remove_omnipresencemodel_update_character_activity_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='omnipresencemodel',
            name='update_character_activity',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='omnipresencemodel',
            trigger=pgtrigger.compiler.Trigger(name='update_character_activity', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    NEW.is_active = True; RETURN NEW;\n                ', hash='72a0876740db4e5d08189b454938d4f4519d8251', operation='UPDATE', pgid='pgtrigger_update_character_activity_00ac2', table='omnipresence_omnipresencemodel', when='BEFORE')),
        ),
    ]
