# Generated by Django 5.0.6 on 2024-06-05 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0002_rename_name_omnipresencemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omnipresencemodel',
            old_name='char',
            new_name='charname',
        ),
        migrations.RenameField(
            model_name='omnipresencemodel',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='omnipresencemodel',
            old_name='cwd',
            new_name='working_dir',
        ),
        migrations.AddField(
            model_name='omnipresencemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnipresencemodel',
            name='last_active',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
