# Generated by Django 5.0.6 on 2024-06-11 00:03

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0003_remove_omnipresencemodel_update_character_activity_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='omnipresencemodel',
            name='update_character_activity',
        ),
    ]
