# Generated by Django 5.0.6 on 2024-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0003_rename_char_omnipresencemodel_charname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='charname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
