# Generated by Django 5.0.6 on 2024-06-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0005_alter_omnipresencemodel_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
