# Generated by Django 5.0.6 on 2024-06-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0006_alter_omnipresencemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='charname',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='omnipresencemodel',
            constraint=models.UniqueConstraint(fields=('charname',), name='charname_field_uniq'),
        ),
    ]
