# Generated by Django 5.0.6 on 2024-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0007_alter_omnipresencemodel_charname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='omnipresencemodel',
            name='charname_field_uniq',
        ),
    ]
