# Generated by Django 5.0.6 on 2024-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipresence', '0008_remove_omnipresencemodel_charname_field_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnipresencemodel',
            name='charname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
